title: "Oussama Ennafii"
copyright_name: "Oussama Ennafii"
description: "Personnal website of Oussama Ennafii."
keywords: "Oussama Ennafii, Personal website, vCard, Researcher, Programmer"
baseurl: ""
url: "https://oussama-ennafii.com"

# Locale settings
timezone: Africa/Casablanca
encoding: utf-8

# Build settings
kramdown:
    input: GFM
highlighter: rouge
permalink: pretty

include:
    - .htaccess
    - _pages
    - files

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor

plugins:
    - jekyll-feed

sass:
    sass_dir: assets/css
    style: compressed
