# Site settings
title: Oussama Ennafii
header-img: img/home-bg.jpg
email: oussama.ennafii@outlook.com
copyright_name: Oussama ennafii
description: "Personnal website."
baseurl: ""
url: "http://ethiy.github.io"
twitter_username: SBootstrap
github_username:  Ethiy
facebook_username:  StartBootstrap
email_username:  oussama.ennafii@outlook.com

# Google Analytics
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
