# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Oussama Ennafii
email: oussama.ennafii@outlook.com
copyright_name: Oussama Ennafii
description: "Personnal website for Oussama Ennafii."
baseurl: ""
url: "https://oussama-ennafii.com"
github_username:  ethiy
linkedin_username: oussama-ennafii
email_username:  oussama.ennafii@outlook.com

# Build settings
kramdown:
    input: GFM
highlighter: rouge
permalink: pretty

include:
    - _pages
plugins:
    - jekyll-feed

sass:
    sass_dir: _sass

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
