# Site settings
title: Oussama Ennafii
header-img: img/karaouiyine.jpg
email: oussama.ennafii@outlook.com
copyright_name: Oussama Ennafii
description: "Personnal website."
baseurl: ""
url: "http://ethiy.github.io"
twitter_username:
github_username:  Ethiy
facebook_username: 
linkedin_username: oussama-ennafii
email_username:  oussama.ennafii@outlook.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
