title: Oussama Ennafii
email: oussama.ennafii@outlook.com
copyright_name: Oussama Ennafii
description: "Personnal website for Oussama Ennafii."
keywords: "Oussama Ennafii, Personal website, vCard, Researcher, Programmer"
baseurl: ""
url: "https://oussama-ennafii.com"

timezone: Africa/Casablanca
encoding: utf-8

include:
    - .htaccess
    - _pages
    - files

# Social networks
social:
    github:  ethiy
    linkedin: oussama-ennafii
    email:  oussama.ennafii@outlook.com

# Build settings
kramdown:
    input: GFM
highlighter: rouge
permalink: pretty

include:
    - _pages
plugins:
    - jekyll-feed

sass:
    sass_dir: _sass

exclude:
    - .sass-cache/
    - .jekyll-cache/
    - gemfiles/
    - Gemfile
    - Gemfile.lock
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
